version: "3"

services:
  database:
    image: "postgres:17"
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - postgresql:/var/lib/postgresql/data/
      # - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  postgres-network:
    name: postgres
    driver: bridge

volumes:
  postgresql:
  pgadmin:
